package web

import (
	"bytes"
	"html/template"

	"github.com/yuin/goldmark"
)

// markdownRenderer converts CommonMark without the Unsafe option, so raw
// HTML in user content is escaped rather than passed through.
var markdownRenderer = goldmark.New()

// renderMarkdown converts markdown source to HTML. The result is safe to
// wrap in template.HTML: goldmark (Unsafe disabled) escapes verbatim user
// HTML, and everything else in the output is markup generated by the
// renderer itself — user content is never bypassed unescaped.
func renderMarkdown(src []byte) (template.HTML, error) {
	var buf bytes.Buffer
	if err := markdownRenderer.Convert(src, &buf); err != nil {
		return "", err
	}
	return template.HTML(buf.String()), nil
}
